### PR TITLE
Add a validator for PrintMessage method.

### PR DESCRIPTION
**Pull request by ALiwoto**
This pull request add a small validator for PrintMessage method; if the string input's length is less than 5, it will print out an error message.

### CODE REVIEW

**Comment by Mehrdadfaridi91** [comment]
Such a wow

**Comment by Mehrdadfaridi91** [comment]
Awesome

**Review by EM80AFR — COMMENTED** [review]
it's very good thanks

**Review by EM80AFR — COMMENTED** [review]
it's very good thanks

**Pull request merged**
